version: 2
project_name: scorecard
env:
  - CGO_ENABLED=0
  - COSIGN_YES=true
before:
  hooks:
    - go mod download
gomod:
  proxy: true

builds:
  - main: .
    binary: pareto
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X paretosecurity.com/auditor/shared.Version={{.Version}}
      - -trimpath
      - -tags=netgo
archives:
  - builds: [pareto]

nfpms:
  - vendor: niteo.co
    homepage: https://github.com/paretosecurity/pareto-linux
    maintainer: NIteo
    description: Automatically audit your Linux machine for basic security hygiene.
    license: MIT
    formats: [deb, rpm, apk]
    bindir: /usr/bin
