# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: paretosecurity
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    tags:
      - menubar
    flags:
      - -v
      - -trimpath
    gcflags:
      - all=-trimpath=${GOPATH}
    ldflags:
      - -s -w
      - -X github.com/ParetoSecurity/pareto-linux/shared.Version={{.Version}}
      - -X github.com/ParetoSecurity/pareto-linux/shared.Commit={{.Commit}}
      - -X github.com/ParetoSecurity/pareto-linux/shared.Date={{.Date}}
    binary: paretosecurity

archives:
  - builds: [pareto]
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README*
nfpms:
  - vendor: niteo.co
    homepage: https://github.com/paretosecurity/pareto-linux
    maintainer: Niteo
    description: Automatically audit your Linux machine for basic security hygiene.
    license: GPL3
    formats: [deb, rpm]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}.{{ .Format }}"
    dependencies:
      - curl
    scripts:
      postinstall: "apt/postinstall.sh"
    contents:
      - src: apt/ParetoSecurity.desktop
        dst: /usr/share/applications/ParetoSecurity.desktop
      - src: assets/Mac_512pt@2x.png
        dst: /usr/share/icons/hicolor/512x512/apps/ParetoSecurity.png
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

aurs:
  - name: paretosecurity-bin
    homepage: "https://github.com/paretosecurity/pareto-linux"
    description: Automatically audit your Linux machine for basic security hygiene.
    maintainers:
      - "paretosecurity"
    contributors:
      - "paretosecurity"
    license: GPL3
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/paretosecurity.git"
    skip_upload: true
    commit_author:
      name: paretosecurity Bot
      email: paretosecurity-bot@users.noreply.github.com
    commit_msg_template: "Update for {{ .ProjectName }} version {{ .Tag }}"
    url_template: "https://github.com/paretosecurity/pareto-linux/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      install -Dm 0755 "${srcdir}"/paretosecurity "${pkgdir}"/usr/bin/paretosecurity
      install -Dm 0644 "${srcdir}"/LICENSE "${pkgdir}"/usr/share/licenses/$pkgname/LICENSE
      install -Dm 0644 "${srcdir}"/README.md "${pkgdir}"/usr/share/doc/$pkgname/README.md

      # Create socket unit
      cat << 'EOF' | tee ${pkgdir}/usr/lib/systemd/system/pareto-linux.socket > /dev/null
      [Unit]
      Description=Socket for pareto-linux

      [Socket]
      ListenStream=/var/run/pareto-linux.sock
      SocketMode=0666
      Accept=no

      [Install]
      WantedBy=sockets.target
      EOF

      # Create service unit
      cat << 'EOF' | tee ${pkgdir}/usr/lib/systemd/system/pareto-linux.service > /dev/null
      [Unit]
      Description=Service for pareto-linux
      Requires=pareto-linux.socket

      [Service]
      ExecStart=/usr/bin/paretosecurity helper --verbose --socket /var/run/pareto-linux.sock
      User=root
      Group=root
      StandardInput=socket
      Type=oneshot
      RemainAfterExit=no
      StartLimitInterval=1
      StartLimitBurst=100

      # Disabled to allow cehcking firewall rules
      #ReadOnlyPaths=/

      ProtectSystem=full
      ProtectHome=yes
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target
      EOF

      # Reload systemd and enable socket
      systemctl daemon-reload
      systemctl enable pareto-linux.socket
      systemctl start pareto-linux.socket
