# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: paretosecurity
before:
  hooks:
  - go mod tidy
  - go tool go-winres make --product-version=git-tag --file-version=git-tag --arch="amd64,386,arm64"
  - sh -c "cp *.syso cmd/paretosecurity/"
  - sh -c "cp *.syso cmd/paretosecurity-tray/"
  - sh -c "cp *.syso cmd/paretosecurity-installer/"

builds:
- main: ./cmd/paretosecurity
  id: agent
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -v
  - -trimpath
  - -mod=readonly
  gcflags:
  - all=-trimpath=${GOPATH} -l -B
  ldflags:
  - -s -w
  - -X github.com/ParetoSecurity/agent/shared.Version={{.Version}}
  - -X github.com/ParetoSecurity/agent/shared.Commit={{.Commit}}
  - -X github.com/ParetoSecurity/agent/shared.Date={{.Date}}
  binary: paretosecurity
- main: ./cmd/paretosecurity-tray
  id: tray
  env:
  - CGO_ENABLED=0
  - GOPROXY=https://proxy.golang.org,direct
  - GOSUMDB=sum.golang.org
  goos:
  - windows
  goarch:
  - amd64
  flags:
  - -v
  - -trimpath
  - -buildvcs=false
  - -mod=readonly
  gcflags:
  - all=-trimpath=${GOPATH} -l -B
  ldflags:
  - -s -w
  - -H windowsgui -buildid=
  - -X github.com/ParetoSecurity/agent/shared.Version={{.Version}}
  - -X github.com/ParetoSecurity/agent/shared.Commit={{.Commit}}
  - -X github.com/ParetoSecurity/agent/shared.Date={{.Date}}
  binary: paretosecurity-tray
- main: ./cmd/paretosecurity-installer
  id: installer
  env:
  - CGO_ENABLED=0
  - GOPROXY=https://proxy.golang.org,direct
  - GOSUMDB=sum.golang.org
  goos:
  - windows
  goarch:
  - amd64
  flags:
  - -v
  - -trimpath
  - -buildvcs=false
  - -mod=readonly
  tags:
  - production
  - desktop
  gcflags:
  - all=-trimpath=${GOPATH} -l -B
  ldflags:
  - -s -w
  - -H windowsgui -buildid=
  - -X github.com/ParetoSecurity/agent/shared.Version={{.Version}}
  - -X github.com/ParetoSecurity/agent/shared.Commit={{.Commit}}
  - -X github.com/ParetoSecurity/agent/shared.Date={{.Date}}
  binary: paretosecurity-installer

# chocolateys:
# - name: paretosecurity
#   owners: Niteo GmbH
#   title: Pareto Security
#   authors: Niteo GmbH
#   project_url: https://paretosecurity.com
#   package_source_url: https://github.com/ParetoSecurity/agent
#   description: |
#     {{ .ProjectName }} installer package.
#     Automatically audit your device for basic security hygiene.
#   skip_publish: false

upx:
- enabled: false
  brute: true
  compress: best
  ids:
  - installer
  goos:
  - windows

archives:
- format: binary

nfpms:
- vendor: paretosecurity.com
  builds: [ agent ]
  homepage: https://github.com/ParetoSecurity/agent
  maintainer: Pareto Security
  description: Automatically audit your Linux machine for basic security hygiene.
  license: GPL3
  formats: [ deb, rpm, apk, archlinux ]
  bindir: /usr/bin
  file_name_template: "{{ .ProjectName }}_{{ .Arch }}.{{ .Format }}"
  dependencies:
  - curl
  scripts:
    postinstall: "apt/postinstall.sh"
  contents:
  # Desktop files
  - src: apt/ParetoSecurity.desktop
    dst: /usr/share/applications/ParetoSecurity.desktop
  - src: apt/ParetoSecurityLink.desktop
    dst: /usr/share/applications/ParetoSecurityLink.desktop
  # Icons
  - src: assets/icon.png
    dst: /usr/share/icons/hicolor/512x512/apps/ParetoSecurity.png
  # Services
  - src: apt/paretosecurity.service
    dst: /etc/systemd/system/paretosecurity.service
  - src: apt/paretosecurity.socket
    dst: /etc/systemd/system/paretosecurity.socket
  - src: apt/paretosecurity-trayicon.service
    dst: /usr/lib/systemd/user/paretosecurity-trayicon.service
  - src: apt/paretosecurity-user.service
    dst: /usr/lib/systemd/user/paretosecurity-user.service
  - src: apt/paretosecurity-user.timer
    dst: /usr/lib/systemd/user/paretosecurity-user.timer

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
release:
  header: |
    ## Release {{ .Version }}

    #### Installing on Linux (Debian, Fedora, ArchLinux, NixOS, etc.)
    ```bash
    curl -sL pkg.paretosecurity.com/install.sh | sudo bash
    ```

    #### Installing on Windows (Windows 10, Windows 11)

    Download the {{ .Version }} release  from [here](https://github.com/ParetoSecurity/agent/releases/download/{{ .Version }}/paretosecurity-installer-amd64.exe)
