// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LinkService provides the Wails service for device linking
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

/**
 * LinkDevice links this device to a team using the invite ID
 */
export function LinkDevice(inviteID: string, host: string): $CancellablePromise<void> {
    return $Call.ByName("main.LinkService.LinkDevice", inviteID, host);
}

/**
 * QuitApp closes the application
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByName("main.LinkService.QuitApp");
}
