name: "Devenv setup"
description: "Setup devenv for running tests and linters"
inputs:
  authToken:
    description: "Cachix auth token"
    required: true
  devenv:
    description: "Devenv version to install"
    required: false
    default: "github:cachix/devenv/v1.4"
runs:
  using: "composite"
  steps:
  - name: namespacelabs/nscloud-cache-action cannot mkdir /nix so we do it manually
    shell: bash
    run: |
      sudo mkdir /nix
      sudo chown $USER /nix

  - uses: namespacelabs/nscloud-cache-action@v1
    with:
      path: |
        /home/runner/go/pkg/mod
        /nix
        ~/.cache
        .devenv

  - uses: cachix/install-nix-action@v31
    with:
      extra_nix_config: |
        system-features = kvm nixos-test

  - name: Install devenv.sh
    shell: bash
    run: |
      if ! command -v devenv &> /dev/null; then
        nix profile install --accept-flake-config ${{ inputs.devenv }}
      fi
