on:
  repository_dispatch:
    types: [integration-test]
  workflow_dispatch:

jobs:
  integration:
    name: Test on ${{ matrix.os }}
    runs-on: namespace-profile-pareto-linux
    strategy:
      matrix:
        os: [ubuntu, debian, fedora]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/devenv
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run .#test-release-${{ matrix.os }}
