name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC

jobs:
  check-on-nix:
    name: "Check: ${{ matrix.check }}"
    runs-on: namespace-profile-pareto-linux
    strategy:
      fail-fast: false
      matrix:
        check: [pwd-manager, firewall, screenlock, secureboot, luks, help]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/devenv
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: chmod o+rx /home/runner
        name: Update /home/runner permissions so that Nix is happy

      - run: nix build .#checks.x86_64-linux.${{ matrix.check }} --print-build-logs
        env:
            NIX_PAGER: cat
